package main

const (
	// Version denotes the current application version.
	Version = "1.0.0"

	// --- Core Paths ---

	// BackupFilePath is where the ephemeral rollback archive is stored during transactions.
	BackupFilePath = "/var/lib/envycontrol/backup.tar.gz"

	// --- Config Paths ---

	BlacklistPath      = "/etc/modprobe.d/blacklist-nvidia.conf"
	UdevIntegratedPath = "/etc/udev/rules.d/50-remove-nvidia.rules"
	UdevPmPath         = "/etc/udev/rules.d/80-nvidia-pm.rules"
	XorgPath           = "/etc/X11/xorg.conf"
	ModesetPath        = "/etc/modprobe.d/nvidia.conf"

	// --- Templates ---

	BlacklistContent = `# Automatically generated by EnvyControl

blacklist nouveau
blacklist nova_core
blacklist nova_drm
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_uvm
blacklist nvidia_modeset
blacklist nvidia_current
blacklist nvidia_current_drm
blacklist nvidia_current_uvm
blacklist nvidia_current_modeset
blacklist i2c_nvidia_gpu
alias nouveau off
alias nova_core off
alias nova_drm off
alias nvidia off
alias nvidia_drm off
alias nvidia_uvm off
alias nvidia_modeset off
alias nvidia_current off
alias nvidia_current_drm off
alias nvidia_current_uvm off
alias nvidia_current_modeset off
alias i2c_nvidia_gpu off
`

	UdevIntegrated = `# Automatically generated by EnvyControl

ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{power/control}="auto", ATTR{remove}="1"
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{power/control}="auto", ATTR{remove}="1"
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{power/control}="auto", ATTR{remove}="1"
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x03[0-9]*", ATTR{power/control}="auto", ATTR{remove}="1"
`

	UdevPmContent = `# Automatically generated by EnvyControl

ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{remove}="1"
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{remove}="1"
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{remove}="1"

ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="auto"

ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="on"
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="on"
`

	XorgIntel = `# Automatically generated by EnvyControl
Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "intel"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "%s"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration"
EndSection

Section "Device"
    Identifier "intel"
    Driver "modesetting"
EndSection

Section "Screen"
    Identifier "intel"
    Device "intel"
EndSection
`

	XorgAmd = `# Automatically generated by EnvyControl
Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "amdgpu"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "%s"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration"
EndSection

Section "Device"
    Identifier "amdgpu"
    Driver "amdgpu"
EndSection

Section "Screen"
    Identifier "amd"
    Device "amdgpu"
EndSection
`

	// Modeset configs use %s to dynamically inject the Nvidia module name
	// (e.g., "nvidia" or "nvidia-current") defined via the NV_MODULE env var.
	ModesetContent = `# Automatically generated by EnvyControl
options %s-drm modeset=1
options %s NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
`

	ModesetRtd3 = `# Automatically generated by EnvyControl
options %s-drm modeset=1
options %s "NVreg_DynamicPowerManagement=0x0%d"
options %s NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
`
)

// --- Validations ---

var (
	SupportedModes = []string{"integrated", "hybrid", "nvidia"}
	Rtd3Modes      = []int{0, 1, 2, 3}
)
