package main

const (
	// Version denotes the current application version.
	// The -v2 suffix indicates the Go-native architectural rewrite.
	Version = "3.5.2-v2"

	// --- Core Paths ---

	// StateFilePath is where the application stores its Source of Truth.
	StateFilePath = "/etc/envycontrol/state.json"
	// BackupFilePath is where the ephemeral rollback archive is stored during transactions.
	BackupFilePath = "/var/lib/envycontrol/backup.tar.gz"

	// --- Config Paths ---

	BlacklistPath      = "/etc/modprobe.d/blacklist-nvidia.conf"
	UdevIntegratedPath = "/etc/udev/rules.d/50-remove-nvidia.rules"
	UdevPmPath         = "/etc/udev/rules.d/80-nvidia-pm.rules"
	XorgPath           = "/etc/X11/xorg.conf"
	ExtraXorgPath      = "/etc/X11/xorg.conf.d/10-nvidia.conf"
	ModesetPath        = "/etc/modprobe.d/nvidia.conf"
	SddmXsetupPath     = "/usr/share/sddm/scripts/Xsetup"
	LightdmScriptPath  = "/etc/lightdm/nvidia.sh"
	LightdmConfigPath  = "/etc/lightdm/lightdm.conf.d/20-nvidia.conf"

	// --- Templates ---

	BlacklistContent = `# Automatically generated by EnvyControl

blacklist nouveau
blacklist nova_core
blacklist nova_drm
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_uvm
blacklist nvidia_modeset
blacklist nvidia_current
blacklist nvidia_current_drm
blacklist nvidia_current_uvm
blacklist nvidia_current_modeset
blacklist i2c_nvidia_gpu
alias nouveau off
alias nova_core off
alias nova_drm off
alias nvidia off
alias nvidia_drm off
alias nvidia_uvm off
alias nvidia_modeset off
alias nvidia_current off
alias nvidia_current_drm off
alias nvidia_current_uvm off
alias nvidia_current_modeset off
alias i2c_nvidia_gpu off
`

	UdevIntegrated = `# Automatically generated by EnvyControl

ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{power/control}="auto", ATTR{remove}="1"
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{power/control}="auto", ATTR{remove}="1"
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{power/control}="auto", ATTR{remove}="1"
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x03[0-9]*", ATTR{power/control}="auto", ATTR{remove}="1"
`

	UdevPmContent = `# Automatically generated by EnvyControl

ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c0330", ATTR{remove}="1"
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x0c8000", ATTR{remove}="1"
ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x040300", ATTR{remove}="1"

ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="auto"
ACTION=="bind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="auto"

ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030000", TEST=="power/control", ATTR{power/control}="on"
ACTION=="unbind", SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{class}=="0x030200", TEST=="power/control", ATTR{power/control}="on"
`

	XorgIntel = `# Automatically generated by EnvyControl
Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "intel"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "%s"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration"
EndSection

Section "Device"
    Identifier "intel"
    Driver "modesetting"
EndSection

Section "Screen"
    Identifier "intel"
    Device "intel"
EndSection
`

	XorgAmd = `# Automatically generated by EnvyControl
Section "ServerLayout"
    Identifier "layout"
    Screen 0 "nvidia"
    Inactive "amdgpu"
EndSection

Section "Device"
    Identifier "nvidia"
    Driver "nvidia"
    BusID "%s"
EndSection

Section "Screen"
    Identifier "nvidia"
    Device "nvidia"
    Option "AllowEmptyInitialConfiguration"
EndSection

Section "Device"
    Identifier "amdgpu"
    Driver "amdgpu"
EndSection

Section "Screen"
    Identifier "amd"
    Device "amdgpu"
EndSection
`

	ExtraXorgContent = `# Automatically generated by EnvyControl
Section "OutputClass"
    Identifier "nvidia"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
`

	ForceComp = "    Option \"ForceCompositionPipeline\" \"true\"\n"
	Coolbits  = "    Option \"Coolbits\" \"%d\"\n"

	ModesetContent = `# Automatically generated by EnvyControl
options nvidia-drm modeset=1
options nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
`

	ModesetCurrentContent = `# Automatically generated by EnvyControl
options nvidia-current-drm modeset=1
options nvidia-current NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
`

	ModesetRtd3 = `# Automatically generated by EnvyControl
options nvidia-drm modeset=1
options nvidia "NVreg_DynamicPowerManagement=0x0%d"
options nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
`

	ModesetCurrentRtd3 = `# Automatically generated by EnvyControl
options nvidia-current-drm modeset=1
options nvidia-current "NVreg_DynamicPowerManagement=0x0%d"
options nvidia-current NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0
`

	SddmXsetupContent = `#!/bin/sh
# Xsetup - run as root before the login dialog appears

`

	LightdmConfigContent = `# Automatically generated by EnvyControl
[Seat:*]
display-setup-script=/etc/lightdm/nvidia.sh
`

	NvidiaXrandrScript = `#!/bin/sh
# Automatically generated by EnvyControl
current=""
xrandr --setprovideroutputsource "%s" NVIDIA-0
xrandr --auto
for next in $(xrandr --listmonitors | grep -E " *[0-9]+:.*" | cut -d" " -f6); do
  [ -z "$current" ] && current=$next && continue
  xrandr --output "$current" --auto --output "$next" --auto --right-of "$current"
  current=$next
done
`
)

// --- Validations ---

var (
	SupportedModes           = []string{"integrated", "hybrid", "nvidia"}
	SupportedDisplayManagers = []string{"gdm", "gdm3", "sddm", "lightdm"}
	Rtd3Modes                = []int{0, 1, 2, 3}
)
