package main

import (
	"archive/tar"
	"compress/gzip"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// ExecuteTransaction acts as a filesystem engine. It safely applies a TransactionPlan
// by first archiving all affected existing files. It returns a slice of paths for all
// files successfully created during this run, aiding in orphaned file cleanup upon rollback.
func ExecuteTransaction(plan TransactionPlan) ([]string, error) {
	LogDebug("Preparing to execute filesystem transaction...")

	var createdFiles []string

	// Phase 1: Snapshot existing configuration
	err := createBackup(plan)
	if err != nil {
		return nil, fmt.Errorf("failed to create backup, aborting transaction: %v", err)
	}
	LogInfo("Created safety backup at %s", BackupFilePath)

	// Phase 2: Clear old files
	for _, path := range plan.ToRemove {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			LogWarning("Failed to remove legacy file %s: %v", path, err)
		} else if err == nil {
			LogDebug("Removed %s", path)
		}
	}

	// Phase 3: Write new files securely
	for _, fileConf := range plan.ToCreate {
		err := atomicWrite(fileConf)
		if err != nil {
			// Fail-Fast: Trigger rollback immediately using files written so far
			LogError("Filesystem error during transaction: %v", err)
			LogError("Triggering Emergency Rollback...")

			if rbErr := RollbackTransaction(createdFiles); rbErr != nil {
				return createdFiles, fmt.Errorf("CRITICAL: transaction failed AND rollback failed: %v", rbErr)
			}
			return createdFiles, fmt.Errorf("transaction failed but system was safely rolled back")
		}

		createdFiles = append(createdFiles, fileConf.Path)
	}

	return createdFiles, nil
}

// atomicWrite guarantees that a file is either fully written or not at all.
// It writes to a temporary file and uses the POSIX atomic rename system call.
func atomicWrite(conf FileConfig) error {
	dir := filepath.Dir(conf.Path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	mode := os.FileMode(0644)
	if conf.Executable {
		mode = 0755
	}

	tmpPath := conf.Path + ".tmp"

	// Write data to the temporary file
	if err := os.WriteFile(tmpPath, []byte(conf.Content), mode); err != nil {
		return err
	}
	defer func() { _ = os.Remove(tmpPath) }() // Cleanup tmp file on failure

	// Explicitly apply executable permissions if required
	if conf.Executable {
		if err := os.Chmod(tmpPath, 0755); err != nil {
			return fmt.Errorf("chmod +x failed for %s: %v", tmpPath, err)
		}
	}

	// Atomically overwrite target path
	if err := os.Rename(tmpPath, conf.Path); err != nil {
		return fmt.Errorf("atomic rename failed %s -> %s: %v", tmpPath, conf.Path, err)
	}

	LogInfo("Created file %s", conf.Path)
	return nil
}

// createBackup scans the plan for any files that currently exist on the disk
// and bundles them into an ephemeral tar.gz archive.
func createBackup(plan TransactionPlan) (err error) {
	pathsToBackup := make(map[string]bool)
	for _, p := range plan.ToRemove {
		pathsToBackup[p] = true
	}
	for _, p := range plan.ToCreate {
		pathsToBackup[p.Path] = true
	}

	if err := os.MkdirAll(filepath.Dir(BackupFilePath), 0755); err != nil {
		return fmt.Errorf("failed to create backup directory: %v", err)
	}

	backupFile, err := os.Create(BackupFilePath)
	if err != nil {
		return err
	}
	defer func() {
		closeErr := backupFile.Close()
		if err == nil && closeErr != nil {
			err = fmt.Errorf("failed to flush backup file to disk: %w", closeErr)
		}
	}()

	gw := gzip.NewWriter(backupFile)
	defer func() {
		closeErr := gw.Close()
		if err == nil && closeErr != nil {
			err = fmt.Errorf("failed to flush backup file to disk: %w", closeErr)
		}
	}()

	tw := tar.NewWriter(gw)
	defer func() {
		closeErr := tw.Close()
		if err == nil && closeErr != nil {
			err = fmt.Errorf("failed to flush backup file to disk: %w", closeErr)
		}
	}()

	// Only archive files that actually exist
	for path := range pathsToBackup {
		info, err := os.Stat(path)
		if err == nil && !info.IsDir() {
			header, err := tar.FileInfoHeader(info, info.Name())
			if err != nil {
				return err
			}
			header.Name = path // Preserve the absolute file path inside the tar

			if err := tw.WriteHeader(header); err != nil {
				return err
			}

			file, err := os.Open(path)
			if err != nil {
				return err
			}

			_, err = io.Copy(tw, file)
			if err != nil {
				return err
			}

			err = file.Close()
			if err != nil {
				return err
			}
			LogDebug("Backed up %s", path)
		}
	}

	return nil
}

// RollbackTransaction acts as the system's failsafe. It deletes any orphaned files
// generated during the faulty transaction, then extracts the safety archive to restore
// the original filesystem state.
func RollbackTransaction(createdFiles []string) error {
	LogInfo("Starting rollback process...")

	// 1. Clean up orphaned files newly generated by the failed transaction
	for _, f := range createdFiles {
		if err := os.Remove(f); err == nil {
			LogDebug("Rollback: Removed orphaned file %s", f)
		}
	}

	// 2. Abort if no backup exists to restore
	if _, err := os.Stat(BackupFilePath); os.IsNotExist(err) {
		return fmt.Errorf("no backup found at %s", BackupFilePath)
	}

	backupFile, err := os.Open(BackupFilePath)
	if err != nil {
		return err
	}
	defer func() { _ = backupFile.Close() }()

	gr, err := gzip.NewReader(backupFile)
	if err != nil {
		return err
	}
	defer func() { _ = gr.Close() }()

	tr := tar.NewReader(gr)

	// 3. Extract and overwrite the filesystem with legacy configurations
	for {
		header, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}

		targetPath := header.Name
		if targetPath == "" {
			continue
		}

		// Recreate parent directories in case they were lost
		if err := os.MkdirAll(filepath.Dir(targetPath), 0755); err != nil {
			return fmt.Errorf("failed to create %s's parent directory: %v", targetPath, err)
		}

		file, err := os.OpenFile(targetPath, os.O_CREATE|os.O_RDWR|os.O_TRUNC, os.FileMode(header.Mode))
		if err != nil {
			return err
		}

		if _, err := io.Copy(file, tr); err != nil {
			_ = file.Close()
			return err
		}

		if err := file.Close(); err != nil {
			return err
		}

		LogWarning("Rolled back file: %s", targetPath)
	}

	LogInfo("Rollback completed successfully. System state restored.")
	return nil
}
